apiVersion: apps/v1
kind: Deployment
metadata:
  name: regcleaner
  labels:
    app: regcleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regcleaner
  template:
    metadata:
      labels:
        app: regcleaner
        aadpodidbinding: secret-identity
    spec:
      containers:
      - name: regcleaner
        image: polyengcr.azurecr.io/regcleanerscheduler:20220419211752
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        env:
          - name: "RegEndpoint"
            value: "https://polyengcr.azurecr.io"
          - name: "MonthBack"
            value: "-3"
          - name: "CosmosDbName"
            value: "acrdb"
          - name: "CosmosDbAccountName"
            value: "container-da"
          - name: "CosmosContainerName"
            value: "testcontainer"
          - name: "SubscriptionId"
            value: "a9f4e502-9188-4e9c-857f-532dd66f5d0c"
          - name: "ResourceGroup"
            value: "PolyTstUseGc"

         



         
          
       